### ISSUE TITLE
fillgap bug

### ISSUE THREAD

**Issue by ktugan** [BioroboticsLab/beesbook_backend#12]
```python
Internal Server Error: /plotter/plot_video/
Traceback (most recent call last):
  File "/home/ktugan/miniconda3/envs/backend/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/ktugan/miniconda3/envs/backend/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ktugan/miniconda3/envs/backend/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ktugan/miniconda3/envs/backend/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ktugan/beesbook_backend/plotter/views.py", line 79, in plot_video
    path = Frame.plot_video(data, fill_gap, crop)
  File "/home/ktugan/beesbook_backend/plotter/utils.py", line 35, in check_file
    mem_object = f.call_and_shelve(*args, **kwargs)
  File "/home/ktugan/miniconda3/envs/backend/lib/python3.6/site-packages/joblib/memory.py", line 476, in call_and_shelve
    _, argument_hash, metadata = self._cached_call(args, kwargs)
  File "/home/ktugan/miniconda3/envs/backend/lib/python3.6/site-packages/joblib/memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/home/ktugan/miniconda3/envs/backend/lib/python3.6/site-packages/joblib/memory.py", line 675, in call
    output = self.func(*args, **kwargs)
  File "/home/ktugan/beesbook_backend/plotter/models.py", line 113, in plot_video
    return media.plot_video(data, crop)
  File "/home/ktugan/beesbook_backend/plotter/media.py", line 216, in plot_video
    xs = [x for p in data for x in p['x']]
  File "/home/ktugan/beesbook_backend/plotter/media.py", line 216, in <listcomp>
    xs = [x for p in data for x in p['x']]
KeyError: 'x'
```

**Comment by ktugan** [comment]
done
